//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAlert
    {
        public int Id { get; set; }
        public int currentStock { get; set; }
        public System.DateTime modification { get; set; }
        public string statusStock { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
